name-template: "Example title - v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
exclude-labels:
  - "skip-changelog"
categories:
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Translation"
    labels:
      - "translation"
  - title: "Dependencies"
    labels:
      - "dependency"
  - title: "Code quality and maintenance"
    labels:
      - "maintenance"
      - "code quality"

  - title: "Development environment and tools"
    label: "dev tools"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/nordicopen/easee_hass/v$RESOLVED_VERSION/total.svg)](https://github.com/nordicopen/easee_hass/releases/v$RESOLVED_VERSION)

  ### Don't forget to run `make lint` and `make bump` before releasing new version

  ## Changes

  $CHANGES

autolabeler:
  - label: "maintenance"
    files:
      - "*.md"

  - label: "dev tools"
    files:
      - ".github/*"
      - ".devcontainer/*"
      - "links.sh"
      - "Makefile"
      - "setup.cfg"
      - "requirements*.txt"
      - ".gitignore"
  - label: "bugfix"
    title:
      - "/fix/i"
  - label: "translation"
    title:
      - "Lokalise:"
    files:
      - "*/translations/*.json"
