ln -s custom_components/easee/__init__.py .
ln -s custom_components/easee/manifest.json .
ln -s custom_components/easee/sensor.py .
ln -s custom_components/easee/controller.py .
ln -s custom_components/easee/entity.py .
ln -s custom_components/easee/const.py .
ln -s custom_components/easee/services.py .
ln -s custom_components/easee/switch.py .
ln -s custom_components/easee/config_flow.py .
ln -s custom_components/easee/services.yaml .
ln -s custom_components/easee/translations .
