default_config:

logger:
  default: info
  logs:
    custom_components.easee: debug
    pyeasee: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy: