#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi
if ! grep -R "^logger:" config/configuration.yaml >> /dev/null;then
echo -n "
logger:
  default: info
  logs:
    custom_components.easee: debug
    pyeasee: debug
" >> config/configuration.yaml
fi
if ! grep -R "debugpy:" config/configuration.yaml >> /dev/null;then
echo "
# Uncomment the line below if you want to use debugger
# debugpy:
" >> config/configuration.yaml
fi


# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/ake_dev
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Start Home Assistant
hass --config "${PWD}/config" --debug
